### ISSUE TITLE
Add total results info to get all interventions call

### ISSUE THREAD

**Issue by chodorowicz** [lightning-team/Ekostraz#124]
To make the pagination work on the FE side we need, total results info in the response of the get all interventions call. Of course this totalCount include elements which are matching with the current filter parameters.

Example response

```json
{
	"count": 123,
	"results: [{}, ...]
}
```

https://ekostrazstagging.azurewebsites.net/api/Swagger/ui#/GetAllInterventions/Run

**Comment by CorneeSean** [comment]
I think that we might also change the filter DTO to accept a list of Statuses instead of  a single Status.
@chodorowicz @przeradalukasz What do you guys think?

**Comment by przeradalukasz** [comment]
Here you go: https://github.com/lightning-team/Ekostraz/pull/129

**Comment by CorneeSean** [comment]
Needed fixing, but works now.
