### ISSUE TITLE
[Backend] Funkcja do notatek

### ISSUE THREAD

**Issue by przeradalukasz** [lightning-team/Ekostraz#16]

**Comment by przeradalukasz** [comment]
@dariuszparzygnat @chodorowicz  O co tu chodziło? nie zrobiliśmy przypadkiem duplikatu i chodzi o komentarze przy interwencji ? Na to wychodzi patrząc w dokument z założeniami.

**Comment by dariuszparzygnat** [comment]
Według mnie to to samo. @chodorowicz  ? @CorneeSean? co myślicie ?
