### ISSUE TITLE
[Frontend] Komentarze

### ISSUE THREAD

**Issue by przeradalukasz** [lightning-team/Ekostraz#17]

**Comment by CorneeSean** [comment]
Basic steps:
1. Displaying existing comments for interventions
2. Adding comments to existing intervention

Additional steps:
Clean-up Interventions details views - single detail and on map

**Comment by chodorowicz** [comment]
https://github.com/lightning-team/Ekostraz/pull/78

**Comment by CorneeSean** [comment]
@chodorowicz Do you maybe plan on following through with #83 ?

**Comment by chodorowicz** [comment]
Yeah, I will do that task 🙂
