### ISSUE TITLE
[Frontend] Responsywne widoki formularza i szczegółów interwencji

### ISSUE THREAD

**Issue by CorneeSean** [lightning-team/Ekostraz#23]
Proste zadanie do zrobienia głównie w CSS (być może trochę HTML)

Katalog z plikami formularza jest [tutaj](https://github.com/lightning-team/Ekostraz/tree/master/frontend/src/app/modules/intervention-form/form)
Formularz jest użyty w 3 miejscach: Publiczny, Prywatny i Edycji.

Katalog z plikami dla szegółów interwencji jest [tutaj](https://github.com/lightning-team/Ekostraz/tree/master/frontend/src/app/modules/interventions/details)
Szczegóły są wyświetlone w dwóch miejscach, które się dość znacznie różnią.
Pierwsze miejsce to niezależny widok po routingu (details.container.component.ts), drugie miejsce to widok embedded w popupie po kliknięciu w znacznik na mapie interwencji

**Comment by chodorowicz** [comment]
@CorneeSean jak mogę uruchomić widok mapy, żeby podejrzeć tam formularz?

**Comment by CorneeSean** [comment]
@chodorowicz widok mapy jest dostępny w pasku menu na górze lub pod przyciskiem na widoku listy po zalogowaniu. Obecnie wystarczy kliknąć 'Zaloguj' na dialogu do logowania. Formularza na mapie nie ma - tylko szczegóły interwencji - po kliknięciu w znacznik wydarzenia.

**Comment by CorneeSean** [comment]
@chodorowicz Pierwszą część z formularzem możemy uznać za zakończoną. Pytanie, czy będziesz się też brał za drugą część dotyczącą "szczegółów interwencji"? To mogło być rozbite na dwa issues, ale chcielismy szybko apkę kończyć podobno to zrobiłem jedno wtedy i teraz nie wiem czy edytować i zamknąć i stworzyć nowe czy jednak o drugiej części też już myślałeś :)

**Comment by CorneeSean** [comment]
Formularz zrobiony, na szczegóły interwencji jest #72
