### ISSUE TITLE
Przy edycji interwencji nie wypełnia się pole Status interwencji

### ISSUE THREAD

**Issue by przeradalukasz** [lightning-team/Ekostraz#25]
Edyctując interwencję z widoku listy lub mapy dropdown pola Status interwencji jest pusty

**Comment by przeradalukasz** [comment]
Widzę że dane brane są z FakeData i tam jest zły typ (w j. polskim). Jak w bazie trzymacie poprawnie (np. ToVerify) to jest ok i do zamknięcia. @patrikulus @CorneeSean

**Comment by CorneeSean** [comment]
Dzięki wielkie za zgłoszenie buga. 
Myślę, że warto poczekać na backend i wtedy przetestować dokładnie formularz jak i całą apkę w miejscach gdzie rzeczywiste dane powinny być pobierane :)

**Comment by CorneeSean** [comment]
Oki, teraz mamy zmienione API backendu i bug dalej istnieje, chociaż z innego powodu niż wcześniej :)
Przy ładowaniu strony do edycji interwencji zwracany z backendu Status jest typu string, a powinien być int/number. Statusy dla Interwencji na liście są zwracane poprawnie - int. Problemem jest prawdopodobnie duplikacja struktur danych na backendzie. Możliwe, że ten PR jest w stanie to naprawić: #71
