### ISSUE TITLE
Podpiąć narzędzie do monitoringu błędów

### ISSUE THREAD

**Issue by CorneeSean** [lightning-team/Ekostraz#28]
Przydałoby się już do pierwszej wersji podpiąć narzędzie do monitoringu błędów.

Raczej myślę o skorzystaniu z gotowych narzędzi zewnętrznych (Sentry (Raven), Rollbar, coś innego?). Napisanie naszego własnego byłoby też osiągalne, ale z racji ograniczonych zasobów czasowych i personalnych chyba nam się to nie opłaca :)

Ktoś z Was korzystał z jakiegoś narzędzia które sprawdzało się dość dobrze i ma także darmowy plan dla małych aplikacji?

**Comment by chodorowicz** [comment]
Ja używałem Bugsnag i LogRocket. LogRocket poza łapaniem błędów nagrywa też sesje użytkowników (można odtwarzać dokładne zachowanie na stronie). O Sentry słyszałem wielokrotnie, to chyba najpopularniejsze rozwiązanie, myśle że Sentry może być jak najbardziej.
