### ISSUE TITLE
Integrate Prettier

### ISSUE THREAD

**Issue by chodorowicz** [lightning-team/Ekostraz#31]

**Comment by chodorowicz** [comment]
@CorneeSean Czy to jest dla Ciebie OK, żeby zintegrować Prettier tak, żeby zmiany/formatowanie były robione automatycznie przy każdym commicie?

**Comment by CorneeSean** [comment]
Pewnie, jakieś pre-commit hooki zapewne masz na myśli? :) Jak bedzie podpięty Prettier to mam też automatyczną integrację z IntelliJ z tego co kojarzę, więc będzie mi na bieżąco formatować w IDE :)

**Comment by CorneeSean** [comment]
Closed by #41
