### ISSUE TITLE
Add CI (Github) to frontend PRs

### ISSUE THREAD

**Issue by chodorowicz** [lightning-team/Ekostraz#40]

**Comment by chodorowicz** [comment]
Another option: https://github.com/apps/codesandbox

**Comment by CorneeSean** [comment]
I see that you had a codesandbox set up, but you dropped it. I guess that it was not suitable for CI? Or GitHub Actions are just easier?

**Comment by chodorowicz** [comment]
Not really the best choice for us, it more suited for libraries, not customer facing projects. And also it wasn't working out of the box.

**Comment by chodorowicz** [comment]
Github Actions is now integrated as CI tool.
