### ISSUE TITLE
Upgrade TS to 3.7 and Angular dependencies

### ISSUE THREAD

**Issue by chodorowicz** [lightning-team/Ekostraz#56]

**Comment by CorneeSean** [comment]
Closed by #57

**Comment by CorneeSean** [comment]
Karma test runner stopped working after update. @chodorowicz Kuba, could you please take a look a this? We can use Jest as you proposed, however as far as I remember there's a slight API mismatch between Jasmine spies and Jest mocks that needs to be taken into consideration.

**Comment by CorneeSean** [comment]
Due to Node issues for Karma tests we'll stay with typescript 3.5.* for now. Closed by #60
