### ISSUE TITLE
Zmiany dotyczące API i filtrowania

### ISSUE THREAD

**Issue by przeradalukasz** [lightning-team/Ekostraz#65]
1. Zmieniono przekazywany adres interwencji ze string Address na trzy propercję: City, Street, StreetNumber (wszystkie typu string).
	2. Dodane endpoint do pobierania jednej interwencji tylko po jej Id (Guid).
	3. Dodane endpoint do edycji interwencji. (dwa endpointy: jeden szukjący tylko po Id, drugi po Id i geohashu). W odpowiedzi przychodzi DTO ze zmienioną interwencją.
	4. Zmiana w interventionDto. Teraz Status wysyłany jest jako int a nie string. 
	5. Dodatkowe endpointy interventions/{interventionId}/comments które można używać bez geohasha.
	6. Pobieranie interwencji dla widoku mapy GetInterventionsInArea ma teraz dodatkowy parametr do filtrowania (więcej w Postman Collection)

**Comment by przeradalukasz** [comment]
https://drive.google.com/file/d/1A5hxZWMv_f4jc_ftHlF-LMIydoAvptOG/view?usp=sharing

**Comment by przeradalukasz** [comment]
https://drive.google.com/file/d/1A5hxZWMv_f4jc_ftHlF-LMIydoAvptOG/view?usp=sharing

**Comment by CorneeSean** [comment]
Dzięki Łukasz za zmiany, przeglądam sobie kolekcję w Postmanie i będę stopniowo przepinał front-end. :)

Powiedz mi jeszcze proszę:
1. Macie dalej tego Swaggera podpiętego także? Jeśli tak, to mógłbyś ten link do niego podrzucić tutaj? Co myślisz o umieszczeniu go w jakimś pliku README albo czymś podobnym w repo?

2. Czy ten plik na Google Drive do kolekcji jest publiczny? Jeśli tak to chyba nam tokeny do funkcji wyciekają wtedy? :)

3. Czy myślisz, że trzymanie pliku z kolekcją do Postmana w repo miałoby jakiś sens (bez tokenów). Wydaje mi się, że dzielenie się kolekcją w ten sposób i jest updateowanie mogłoby być spoko :)

**Comment by CorneeSean** [comment]
Jeszcze odnośnie usunięcia  pliku .editorconfig:
zdaję sobie sprawę, że reguły się tam znajdujące powinny zostać zawężone do katalogu "frontend" i jest to nasz błąd - za co przepraszamy - natomiast wydaje mi się, że mogliśmy to rozwiązać bez usuwania pliku w zupełnie niezwiązanym z tym PR i po prostu o tym pogadać wczesniej :)

Pozwolę sobie przywrócić ten plik w najbliższym PR z odpowiednio zawężonymi regułami - prosiłbym Cię o potwierdzenie czy Wasz kod pozostaje wciąż nienaruszony.

**Comment by CorneeSean** [comment]
Link do PR przywracającej .editorconfig: https://github.com/lightning-team/Ekostraz/pull/66

**Comment by przeradalukasz** [comment]
1. Swagger jest po adresem: https://ekostrazstagging.azurewebsites.net/api/swagger/ui
2 i 3. Plik jest prywatny, tylko pod tym linkiem. Ale przeniosę go do repo razem z aktualizacją ReadMe o info o nim i linkiem do swaggera.

Co do pliku to myślałem że ja albo Darek to zostawiliśmy ;) mogłem sprawdzić kto to wrzucił. Sorry!

I jeszcze zapomniałem. Dodałem swoje konto do GoogleMaps, tam są jakieś $ na rok, wyłączyłem billing więc nie powinno mnie chargować za nic. Można więc dodawać/edytować interwencje.
